application: clock
version: 1
runtime: python27
api_version: 1
threadsafe: false

default_expiration: "5d 12h"

handlers:
- url: /prefs
  script: prefs.py
  login: required
- url: /docs/latest  static_dir: /docs 
  expiration: "12h"
- url: /js/(.*)/code.js 
  static_files: js/code.js 
  expiration: "90d"
- url: /.*
  script: main.py